export const USER_AUTHENTICATION = 'USER_AUTHENTICATION';
export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR';
export const USER_CLEAR_AUTHENTICATION_ERROR = 'USER_CLEAR_AUTHENTICATION_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';
